AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for an EventBridge rule triggered by AWS SSO CreateAccountAssignment events.

Parameters:
  EventBridgeRuleName:
    Type: String
    Description: The name of the EventBridge rule.
    Default: Cerberus

  CerberusEventBusArn:
    Type: String
    Description: The ARN of the Cerberus EventBridge event bus in the target account.
    AllowedPattern: "^arn:aws:events:[a-z0-9-]+:\\d{12}:event-bus/[a-zA-Z0-9-_]+$"
    ConstraintDescription: Must be a valid EventBridge event bus ARN.

Resources:
  EventBridgeRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Ref EventBridgeRuleName
      EventPattern:
        source:
          - "aws.sso"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "sso.amazonaws.com"
          eventName:
            - "CreateAccountAssignment"
      State: ENABLED
      Targets:
        - Arn: !Ref CerberusEventBusArn
          Id: "EventBusTarget"
          RoleArn: !GetAtt EventBridgeTargetRole.Arn

  EventBridgeTargetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "events.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: "EventBridgeTargetPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "events:PutEvents"
                Resource: !Ref CerberusEventBusArn

Outputs:
  EventBridgeRuleArn:
    Description: The ARN of the EventBridge rule.
    Value: !GetAtt EventBridgeRule.Arn
  EventBridgeTargetRoleArn:
    Description: The ARN of the IAM role for the EventBridge rule.
    Value: !GetAtt EventBridgeTargetRole.Arn
